##
## EPITECH PROJECT, 2022
## Epitech-Template
## File description:
## workflow.yml
##

name: "Push to remote"
on:
  push:
    branches:
      - 'dev/**'
jobs:
  deploy:
    name: Deploy to Epitech repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${GITHUB_REF#refs/heads/}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Push to Epitech
        run: |
          git remote add epiRepo git@github.com:Quentin-Desmettre/criterion.git
          git fetch --unshallow
          git push epiRepo main