##
## EPITECH PROJECT, 2022
## Epitech-Template
## File description:
## workflow.yml
##

name: "Push to remote"
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests before pushing to remote
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Run tests (functional and unit)
        run: "make tests_run"

      - name: Run push hooks
        run: "pip install websocket-client && python ./.github/cpp_checker.py --hard"

  deploy:
    name: Deploy to Epitech repo
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Config hosts
        run: "echo '${{ secrets.KNOWN_HOSTS }}' > ~/.ssh/known_hosts"

      - name: Push to Epitech
        run: "git remote add epiRepo git@github.com:Quentin-Desmettre/criterion.git && git push epiRepo main"
